version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-apply-web:
    depends_on: 
      - redis
    build:
      target: development
    image: ffc-sfi-apply-web-development
    container_name: ffc-sfi-apply-web-development
    ports:
      - "3000:3000"
      - "9229:9229"
    environment: 
      REDIS_HOSTNAME: redis
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
