environment: development
name: ffc-sfi-apply-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-apply-web

labels:
  component: web

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-apply-web-config-map

containerSecret:
  name: ffc-sfi-apply-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: high
  replicas: 1
  minReplicas: 2
  maxReplicas: 6
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 40m
  limitMemory: 200Mi
  limitCpu: 500m
  port: 3000
  googleTagManagerKey:
  messageQueueHost: namespace.servicebus.windows.net
  eligibilityTopicAddress: ffc-sfi-eligibility-check
  standardsTopicAddress: ffc-sfi-standards-request
  validateTopicAddress: ffc-sfi-agreement-validate
  calculateTopicAddress: ffc-sfi-agreement-calculate
  submitTopicAddress: ffc-sfi-agreement-submit
  withdrawTopicAddress: ffc-sfi-agreement-withdraw
  parcelSpatialTopicAddress: ffc-sfi-parcel-spatial-request
  parcelStandardTopicAddress: ffc-sfi-parcel-standard-request
  parcelSpatialResponseQueueAddress: ffc-sfi-parcel-spatial-response
  parcelStandardResponseQueueAddress: ffc-sfi-parcel-standard-response
  standardsResponseQueueAddress: ffc-sfi-standards-request-response
  calculateResponseQueueAddress: ffc-sfi-agreement-calculate-response
  eligibilityResponseQueueAddress: ffc-sfi-eligibility-check-response
  agreementCalculatorEndpoint: http://ffc-sfi-agreement-calculator.ffc-sfi
  agreementApiEndpoint: http://ffc-sfi-agreement-api.ffc-sfi
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-sfi-apply-web
  cookiePassword: passwordpasswordpasswordpasswordpassword
  osMapApiKey:
  chApiGateway:
  azureStorageAccountName: sfiland
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  parcelStandardContainer: parcels-standard
  parcelSpatialContainer: parcels-spatial
  defraIdEnabled: true
  defraIdWellKnownUrl: not-a-real-url
  defraIdClientId: not-a-real-clientID
  defraIdClientSecret: not-a-real-clientSecret
  defraIdServiceId: not-a-real-serviceID
  defraIdPolicy: not-a-real-policy
  defraIdRedirectUrl: sign-in-oidc
  apimClientId:
  apimClientSecret:
  apimScope:
  apimOcpSubscriptionKey:
  apimAuthorizationUrl:

ingress:
  class: nginx
  endpoint: ffc-sfi-apply-web
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

aadPodIdentity: true
