environment: development
name: ffc-sfi-apply-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-apply-web

labels:
  component: web

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-apply-web-config-map

containerSecret:
  name: ffc-sfi-apply-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  googleTagManagerKey:
  messageQueueHost: namespace.servicebus.windows.net
  eligibilityTopicAddress: ffc-sfi-eligibility-check
  standardsTopicAddress: ffc-sfi-standards-request
  validateTopicAddress: ffc-sfi-agreement-validate
  calculateTopicAddress: ffc-sfi-agreement-calculate
  submitTopicAddress: ffc-sfi-agreement-submit
  agreementCalculatorEndpoint: http://ffc-sfi-agreement-calculator.ffc-sfi
  sitiAgriEndpoint: http://ffc-sfi-apply-api.ffc-sfi
  useAgreementCalculator: false
  redisHostname: redis-redis-ha.default
  redisPassword: redis
  redisPort: 6379
  redisPartition: ffc-sfi-apply-web
  cookiePassword: passwordpasswordpasswordpasswordpassword

postgresService:
  postgresDb: ffc_sfi_apply_web
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-sfi-apply-web-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

ingress:
  class: nginx
  endpoint: ffc-sfi-apply-web
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true
