environment: development
name: ffc-sfi-apply-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-apply-web

labels:
  component: web

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-apply-web-config-map

containerSecret:
  name: ffc-sfi-apply-web-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  googleTagManagerKey:

ingress:
  class: nginx
  endpoint: ffc-sfi-apply-web
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
