environment: development
name: ffc-sfi-apply-web
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-apply-web

labels:
  component: web

appInsights:
  key:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-sfi-apply-web-config-map

containerSecret:
  name: ffc-sfi-apply-web-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  googleTagManagerKey:
  messageQueueHost:
  eligibilityTopicAddress: ffc-sfi-eligibility-check
  standardsTopicAddress: ffc-sfi-standards-request
  validateTopicAddress: ffc-sfi-agreement-validate
  calculateTopicAddress: ffc-sfi-agreement-calculate
  submitTopicAddress: ffc-sfi-agreement-submit

ingress:
  class: nginx
  endpoint: ffc-sfi-apply-web
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

aadPodIdentity: true
