Feature: Apply for land funding
  Scenario: User can successfully open sign in page
    Given I open the url "/"
    Then I expect that the title contains "Apply for sustainable farming funding - GOV.UK"
    And I expect that element "h1" contains the text "Apply for sustainable farming funding"
    When I click on the button ".govuk-button--start"
    Then I expect that the url contains "/login"
    And I expect that element "h1" contains the text "Sign in"
    When I clear the inputfield "#crn"
    And I add "9867012345" to the inputfield "#crn"
    And I clear the inputfield "#callerId"
    And I add "5100150" to the inputfield "#callerId"
    And I clear the inputfield "#password"
    And I add "kdaihsra" to the inputfield "#password"
    And I click on the element "#submit"
    Then I mock the response for "which-business"
    When I pause for 500ms
    Then I expect that the url contains "/start-application"
    When I click on the button "#start-application"
    Then I expect that the url contains "/task-list"
    When I click on the link "Confirm your land cover details"
    Then I mock the response for "confirm-details"
    When I pause for 500ms
    Then I expect that the url contains "/confirm-details"
    And I click on the element "#isLandCorrect"
    And I click on the element "#submit"
    And I expect that the url contains "/management-control"
    When I click on the element "#managementControlCheck"
    And I click on the element "#submit"
    Then I expect that the url contains "/task-list"
    When I click on the link "Choose funding option"
    Then I mock the response for "what-funding"
    When I pause for 500ms
    Then I expect that the url contains "/what-funding"
