{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-apply-web.config-map") -}}
{{- define "ffc-sfi-apply-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.container.googleTagManagerKey }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  {{- end }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  ELIGIBILITY_TOPIC_ADDRESS: {{ quote .Values.container.eligibilityTopicAddress }}
  STANDARDS_TOPIC_ADDRESS: {{ quote .Values.container.standardsTopicAddress }}
  VALIDATE_TOPIC_ADDRESS: {{ quote .Values.container.validateTopicAddress }}
  CALCULATE_TOPIC_ADDRESS: {{ quote .Values.container.calculateTopicAddress }}
  SUBMIT_TOPIC_ADDRESS: {{ quote .Values.container.submitTopicAddress }}
  WITHDRAW_TOPIC_ADDRESS: {{ quote .Values.container.withdrawTopicAddress }}
  REQUEST_SBI_TOPIC_ADDRESS: {{ quote .Values.container.requestSbiTopicAddress }}
  PARCELSPATIAL_TOPIC_ADDRESS: {{ quote .Values.container.parcelSpatialTopicAddress }}
  PARCEL_TOPIC_ADDRESS: {{ quote .Values.container.parcelTopicAddress }}
  PARCELSTANDARD_TOPIC_ADDRESS: {{ quote .Values.container.parcelStandardTopicAddress }}
  STANDARDSRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.responseStandardsQueueAddress }}
  CALCULATERESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.responseCalculateQueueAddress }}
  PARCELSPATIALRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.parcelSpatialResponseQueueAddress }}
  PARCELRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.parcelResponseQueueAddress }}
  PARCELSTANDARDRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.parcelStandardResponseQueueAddress }}
  ELIGIBILITYRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.responseEligibilityCheckQueueAddress }}
  AGREEMENT_CALCULATOR_ENDPOINT: {{ quote .Values.container.agreementCalculatorEndpoint }}
  AGREEMENT_API_ENDPOINT: {{ quote .Values.container.agreementApiEndpoint }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_PARCEL_STANDARD: {{ quote .Values.container.parcelStandardContainer }}
  AZURE_STORAGE_PARCEL_SPATIAL: {{ quote .Values.container.parcelSpatialContainer }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  {{- if .Values.pr }}
  REDIS_PARTITION: {{ .Values.container.redisPartition }}-{{ .Values.pr }}
  {{ else }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  {{- end }}
  CH_API_GATEWAY: {{ quote .Values.container.chApiGateway }}
  {{- if .Values.container.osMapApiKey }}
  OS_MAP_API_KEY: {{ quote .Values.container.osMapApiKey }}
  {{- end }}
{{- end -}}
