{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-apply-web.config-map") -}}
{{- define "ffc-sfi-apply-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.container.googleTagManagerKey }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  {{- end }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  ELIGIBILITY_TOPIC_ADDRESS: {{ quote .Values.container.eligibilityTopicAddress }}
  STANDARDS_TOPIC_ADDRESS: {{ quote .Values.container.standardsTopicAddress }}
  VALIDATE_TOPIC_ADDRESS: {{ quote .Values.container.validateTopicAddress }}
  CALCULATE_TOPIC_ADDRESS: {{ quote .Values.container.calculateTopicAddress }}
  SUBMIT_TOPIC_ADDRESS: {{ quote .Values.container.submitTopicAddress }}
  WITHDRAW_TOPIC_ADDRESS: {{ quote .Values.container.withdrawTopicAddress }}
  REQUEST_SBI_TOPIC_ADDRESS: {{ quote .Values.container.requestSbiTopicAddress }}
  STANDARDSRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.responseStandardsQueue }}
  CALCULATERESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.responseCalculateQueue }}
  ELIGIBILITY_CHECK_RESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.responseEligibilityCheckQueue }}
  AGREEMENT_CALCULATOR_ENDPOINT: {{ quote .Values.container.agreementCalculatorEndpoint }}
  AGREEMENT_API_ENDPOINT: {{ quote .Values.container.agreementApiEndpoint }}
  {{- if .Values.container.redisHostname }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  {{- end }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
  REDIS_PARTITION: {{ quote .Values.container.redisPartition }}
  CH_API_GATEWAY: {{ quote .Values.container.chApiGateway }}
  {{- if .Values.container.osMapApiKey }}
  OS_MAP_API_KEY: {{ quote .Values.container.osMapApiKey }}
  {{- end }}
{{- end -}}
