{{- include "ffc-helm-library.container-secret" (list . "ffc-sfi-apply-web.container-secret") -}}
{{- define "ffc-sfi-apply-web.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  POSTGRES_USERNAME: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
